#include "../oven/parameter.religo"
#include "../oven/storage.religo"
#include "../oven/default/parameter.religo"
// #include "../../../../lambdas/onOvenDepositReceived/onOvenDepositReceivedInit.religo"
#include "../../../runEntrypointLambda/parameter.religo"
// #include "../oven/default/default.religo"