name: Delphi

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2
  
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run migrate
  unit-tzip-7:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run test -- ./test/unit/tzip-7/**
  unit-bridge:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run test -- ./test/unit/bridge/**
  unit-core:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run test -- ./test/unit/core/** ./test/unit/core/lambdas/** ./test/unit/core/lambdas/tzip-7/**
  unit-oven:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run test -- ./test/unit/oven/**
  integration:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run fix-ligo-version 0.3.0
    - run: npm run sandbox:start &
    - name: Wait 15 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - run: npm run test -- ./test/integration/** ./test/integration/oven/**
